-- ============================================================================
-- SIRAYA Health Navigator - Schema Tabella triage_logs
-- Versione migliorata con tutti i KPI per analisi clinica e performance
-- ============================================================================

-- Elimina tabella esistente se presente (ATTENZIONE: cancella i dati!)
-- DROP TABLE IF EXISTS public.triage_logs CASCADE;

-- Crea tabella triage_logs
CREATE TABLE IF NOT EXISTS public.triage_logs (
  -- Identificatori
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  session_id TEXT NOT NULL,
  
  -- Dati Interazione Base
  user_input TEXT,
  bot_response TEXT,
  
  -- KPI Analisi Clinica (Triage)
  detected_intent TEXT,                    -- Intento rilevato (es: "dolore toracico", "ansia")
  triage_code TEXT,                        -- Codice colore: ROSSO, ARANCIONE, GIALLO, VERDE, BIANCO, NERO
  medical_specialty TEXT,                  -- Specializzazione medica (es: Cardiologia, Ortopedia, Psichiatria)
  suggested_facility_type TEXT,           -- Tipo struttura consigliata (es: Pronto Soccorso, Guardia Medica, CSM)
  reasoning TEXT,                          -- Spiegazione clinica del triage (Fondamentale per audit medico)
  estimated_wait_time TEXT,                -- Tempo attesa stimato (es: "Immediato", "1-2 ore", "Non urgente")
  
  -- KPI Performance Tecnica
  processing_time_ms NUMERIC,              -- Tempo di risposta in millisecondi (Latenza)
  model_version TEXT,                      -- Versione del modello (es: "v4.0", "llama-3.3-70b")
  tokens_used INTEGER,                     -- Consumo token (per calcolo costi) - NULL se non disponibile
  
  -- Metadati Extra
  client_ip TEXT,                          -- IP client (utile per sicurezza o geo-analytics) - NULL se non disponibile
  metadata JSONB DEFAULT '{}'::jsonb       -- Campo flessibile per dati futuri senza cambiare schema
);

-- Creazione indici per velocizzare le dashboard di analisi
CREATE INDEX IF NOT EXISTS idx_triage_logs_triage_code ON public.triage_logs(triage_code);
CREATE INDEX IF NOT EXISTS idx_triage_logs_medical_specialty ON public.triage_logs(medical_specialty);
CREATE INDEX IF NOT EXISTS idx_triage_logs_created_at ON public.triage_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_triage_logs_session_id ON public.triage_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_triage_logs_suggested_facility_type ON public.triage_logs(suggested_facility_type);

-- Abilita Row Level Security (RLS)
ALTER TABLE public.triage_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- POLICY RLS SICURE
-- ============================================================================

-- Rimuovi policy permissive esistenti (se presenti)
DROP POLICY IF EXISTS "Enable insert for anon users" ON public.triage_logs;
DROP POLICY IF EXISTS "Enable public read access" ON public.triage_logs;
DROP POLICY IF EXISTS "Enable read for anon users" ON public.triage_logs;

-- Policy INSERT per utenti anonimi (con vincolo session_id)
CREATE POLICY "anon_insert_triage_logs" 
ON public.triage_logs 
FOR INSERT 
TO anon 
WITH CHECK (session_id IS NOT NULL AND session_id != '');

-- Policy SELECT per utenti anonimi (lettura pubblica per analytics)
CREATE POLICY "anon_select_triage_logs" 
ON public.triage_logs 
FOR SELECT 
TO anon 
USING (true);

-- Policy UPDATE per utenti anonimi (solo sulla propria sessione)
CREATE POLICY "anon_update_own_session" 
ON public.triage_logs 
FOR UPDATE 
TO anon 
USING (session_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'session_id'))
WITH CHECK (session_id = (current_setting('request.jwt.claims', true)::jsonb ->> 'session_id'));

-- ============================================================================
-- COMMENTI SULLE COLONNE (Documentazione)
-- ============================================================================

COMMENT ON TABLE public.triage_logs IS 'Log delle interazioni del chatbot SIRAYA con KPI clinici e tecnici';
COMMENT ON COLUMN public.triage_logs.triage_code IS 'Codice colore triage: ROSSO (critico), ARANCIONE (urgente), GIALLO (differibile), VERDE (non urgente), BIANCO (non sanitario), NERO (salute mentale)';
COMMENT ON COLUMN public.triage_logs.medical_specialty IS 'Specializzazione medica suggerita dal triage (es: Cardiologia, Ortopedia, Psichiatria)';
COMMENT ON COLUMN public.triage_logs.reasoning IS 'Spiegazione clinica del processo decisionale del triage (audit medico)';
COMMENT ON COLUMN public.triage_logs.processing_time_ms IS 'Tempo di elaborazione in millisecondi (KPI performance)';
COMMENT ON COLUMN public.triage_logs.tokens_used IS 'Numero di token utilizzati per la risposta (calcolo costi API)';

